### ISSUE TITLE
Common guidelines for all frameworks

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/development-guidelines#7]
- [ ] naming conventions for folder and files

**Comment by jeangovil** [comment]
I think we should change this to "Common guidelines for React projects." 

A list of things to cover could be:
- Naming conventions
- Folder structure
- Component patterns (e.g., container-component pattern)
- Data fetching
- State management

@amirhouieh @jinhojang6, what do you think?

**Comment by jinhojang6** [comment]
I agree with you @jeangovil

**Comment by amirhouieh** [comment]
This looks good and I agree.
@jeangovil  What happens to  guidelines that are common among all frameworks. For example naming convention for classes or using decorators (yes or no) and as such?
